### PR TITLE
Fix nested json parsing errors

### PR DESCRIPTION
**Pull request by dengelke**
Had some errors from nested json objects

### CODE REVIEW

**Comment by ai** [comment]
Why don't you use `postcss-js` parser for JSON?

This parser is only for CSS files (possibly broken).

**Comment by dengelke** [comment]
Mostly because it needs to handle json in css as well as any broken css

**Comment by ai** [comment]
Got it, you want to use JSON inside CSS

**Comment by ai** [comment]
Thanks. Released in 7.0.1.

**Pull request merged**
